### ISSUE TITLE
Pay, A, Login type button image not found in JP sandbox mode.

### ISSUE THREAD

**Issue by biplobice** [amzn/amazon-pay-sdk-php#67]
You may confirm this from following urls-

- https://images-na.ssl-images-amazon.com/images/G/01/EP/offAmazonPayments/jp/sandbox/prod/image/lwa/gold/medium/PwA.png
- https://images-na.ssl-images-amazon.com/images/G/01/EP/offAmazonPayments/jp/sandbox/prod/image/lwa/gold/medium/Pay.png
- https://images-na.ssl-images-amazon.com/images/G/01/EP/offAmazonPayments/jp/sandbox/prod/image/lwa/gold/medium/A.png
- https://images-na.ssl-images-amazon.com/images/G/01/EP/offAmazonPayments/jp/sandbox/prod/image/lwa/gold/medium/LwA.png
- https://images-na.ssl-images-amazon.com/images/G/01/EP/offAmazonPayments/jp/sandbox/prod/image/lwa/gold/medium/Login.png

**Comment by bjguillot** [comment]
In the JP region, only the "LwA" and "PwA" button types codes are supported, so this is expected behavior.

See the "Button Widget" page from the JP Integration Guide:
https://pay.amazon.com/jp/developer/documentation/lpwa/201953980

The other button type codes ("A", "Pay", "Login") can only be used by merchants outside of Japan.
